language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install --prefer-source

before_script:
  - mysql -uroot -e 'create database zfmodules;'
  - mysql -uroot zfmodules < data/sql/0.sql

script:
  - ./vendor/bin/phpcs --standard=./phpcs.xml -np --report=summary .
  - ./vendor/bin/phpmd . text codesize,unusedcode --exclude data,puphpet,vendor
  - ./vendor/bin/phpunit --configuration phpunit.xml

notifications:
  irc: "irc.freenode.org#zftalk.modules"
