language: php
php:
  - 5.5
  - 5.4
  - hhvm 

before_script:
  - composer update --prefer-source

script:
  - ./vendor/bin/phpcs --standard=./phpcs.xml -np --report=summary .
  - phpunit

notifications:
  irc: "irc.freenode.org#zftalk.modules"
