language: php
php:
  - 5.4
  - 5.5
  - hhvm

install:
  - composer install --prefer-source

script:
  - ./vendor/bin/phpcs --standard=./phpcs.xml -np --report=summary .
  - ./vendor/bin/phpunit --configuration phpunit.xml

notifications:
  irc: "irc.freenode.org#zftalk.modules"
