language: php

sudo: false

php:
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer update --prefer-source

before_script:
  - cp config/autoload/travis.php.local.dist config/autoload/travis.local.php
  - mysql -uroot -e 'create database modules_test;'
  - mysql -uroot modules_test < data/sql/0.sql

script:
  - vendor/bin/php-cs-fixer fix --config-file=./.php_cs --dry-run --diff -v
  - vendor/bin/phpunit --configuration phpunit.xml

notifications:
  irc: "irc.freenode.org#zftalk.modules"
